apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: app
          image: 491377098012.dkr.ecr.us-east-1.amazonaws.com/hybrid-devsecops-etb101:v2
          ports:
            - containerPort: 3000
